services:
  api:
    build: .
    container_name: gestmed_api
    environment:
      DATABASE_URL: ${DATABASE_URL}
      PORT: ${PORT:-3333}
      JWT_SECRET: ${JWT_SECRET}
      RESEND_API_KEY: ${RESEND_API_KEY}
      RESEND_FROM_EMAIL: ${RESEND_FROM_EMAIL}
      R2_ENDPOINT: ${R2_ENDPOINT}
      R2_ACCESS_KEY_ID: ${R2_ACCESS_KEY_ID}
      R2_SECRET_ACCESS_KEY: ${R2_SECRET_ACCESS_KEY}
      R2_BUCKET_NAME: ${R2_BUCKET_NAME}
      PATIENT_ACCESS_URL: ${PATIENT_ACCESS_URL}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
    ports:
      - "${API_BIND_ADDRESS:-0.0.0.0}:${PORT:-3333}:${PORT:-3333}"
    restart: unless-stopped
